# Generated by Django 2.2.12 on 2021-05-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
